apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeploy
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      imagePullSecrets: 
      - name: pull-acr
      containers:
      - name: test-cont
        image: acrpubcon.azurecr.io/node-test:e841d3ac542f45098f8ca5795bde36efd01d8ad5
        ports:
        - containerPort: 6080
