apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeploy
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      imagePullSecrets: 
      - name: pull-acr
      containers:
      - name: test-cont
        image: acrpubcon.azurecr.io/node-test:3920e3c0511ddaab1204fc69ef38e4655560fd45
        ports:
        - containerPort: 6080
