apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdeploy
  namespace: default  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testdeploy
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      imagePullSecrets: 
      - name: pull-acr
      containers:
      - name: test-cont
        image: container_registry/node-test:e81d0c3cc1cd51b0bf82a76024879af5083ad793
        ports:
        - containerPort: 6080
